"""Shared, offline Markdown helpers for the public reference generators."""

from __future__ import annotations

import argparse
import html
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
# Explicit provenance, not HEAD: docs-only commits and shallow CI checkouts must
# not change generated bytes. Advance this baseline when documenting a release.
SOURCE_COMMIT = "e1318eca83a40b9418d873ad85c31686ea6b57d0"


def source_link(path: str, line: int | None = None) -> str:
    """Link a repository source path to the reviewed baseline."""
    suffix = f"#L{line}" if line else ""
    return f"https://github.com/Calmingstorm/Odin/blob/{SOURCE_COMMIT}/{path}{suffix}"


def cell(text: object) -> str:
    """Escape prose without allowing Markdown tables or Vue expressions to leak."""
    value = html.escape(str(text), quote=True)
    for char in "\\`*_[]{}|":
        value = value.replace(char, f"&#{ord(char)};")
    return value.replace("\n", "<br>")


def write_or_check(content: str, destination: Path, *, description: str) -> int:
    """CLI shared by both generators; --check never creates or changes files."""
    parser = argparse.ArgumentParser(description=description)
    parser.add_argument("--check", action="store_true", help="Fail if committed output drifts")
    args = parser.parse_args()
    expected = content.encode("utf-8")
    relative = destination.relative_to(REPO_ROOT)
    if args.check:
        if not destination.is_file() or destination.read_bytes() != expected:
            print(f"Reference drift: regenerate {relative}")
            return 1
        print(f"Reference is current: {relative}")
        return 0
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_bytes(expected)
    print(f"Generated {relative}")
    return 0
