; Odin for Windows installs for the current user only (phase 4, P7). electron-builder's per-user
; one-click installer compiles no per-machine branch; these refusals cover the rest, before anything
; is written. A refusal exits with code 2, and a silent install's message box answers itself.

!ifndef BUILD_UNINSTALLER
  Var odinRecordedLocation
!endif

!macro odinRefuse MESSAGE
  MessageBox MB_OK|MB_ICONSTOP "${MESSAGE}" /SD IDOK
  SetErrorLevel 2
  Quit
!macroend

!macro preInit
  ; The uninstaller is generated by running this script at build time; only the installer refuses.
  !ifndef BUILD_UNINSTALLER
    ${GetParameters} $R0
    ClearErrors
    ${GetOptions} $R0 "/allusers" $R1
    ${IfNot} ${Errors}
      !insertmacro odinRefuse "Odin for Windows installs for your account only, so /allusers isn't supported."
    ${EndIf}
    ${StdUtils.GetParameter} $R1 "D" ""
    ${If} $R1 != ""
      !insertmacro odinRefuse "Odin installs into its own folder in your account, so /D isn't supported."
    ${EndIf}
    ; The app's own start check (P9b): this token's TokenElevation, then its default owner (who owns
    ; what it creates) against its user. Anything unreadable refuses too.
    StrCpy $R2 "unchecked"
    System::Call 'kernel32::GetCurrentProcess() p .r9'
    System::Call 'advapi32::OpenProcessToken(p r9, i 8, *p .r1) i .r0'
    ${If} $0 <> 0
      System::Call 'advapi32::GetTokenInformation(p r1, i 20, *i .r2, i 4, *i .r3) i .r0'
      ${If} $0 <> 0
        ${If} $2 <> 0
          StrCpy $R2 "elevated"
        ${Else}
          System::Alloc 1024
          Pop $4
          System::Alloc 1024
          Pop $5
          System::Call 'advapi32::GetTokenInformation(p r1, i 4, p r4, i 1024, *i .r3) i .r0'
          System::Call 'advapi32::GetTokenInformation(p r1, i 1, p r5, i 1024, *i .r3) i .r6'
          ${If} $0 <> 0
          ${AndIf} $6 <> 0
            ; TOKEN_OWNER and TOKEN_USER both start with the SID pointer.
            System::Call '*$4(p .r7)'
            System::Call '*$5(p .r8)'
            System::Call 'advapi32::EqualSid(p r7, p r8) i .r0'
            ${If} $0 <> 0
              StrCpy $R2 "normal"
            ${Else}
              StrCpy $R2 "owner"
            ${EndIf}
          ${EndIf}
          System::Free $4
          System::Free $5
        ${EndIf}
      ${EndIf}
      System::Call 'kernel32::CloseHandle(p r1)'
    ${EndIf}
    ${If} $R2 == "elevated"
      !insertmacro odinRefuse "Odin's installer was started as administrator, so it stopped. Run it normally, without $\"Run as administrator$\": Odin installs for your account, and what an elevated installer creates belongs to Administrators."
    ${ElseIf} $R2 == "owner"
      !insertmacro odinRefuse "Windows would make what this installer creates belong to another account, not yours, so it stopped. Run it from your own account, without $\"Run as administrator$\"."
    ${ElseIf} $R2 != "normal"
      !insertmacro odinRefuse "The installer couldn't check whether it was started as administrator, so it stopped. Run it again normally."
    ${EndIf}
    ; electron-builder 26.0.12 finds a first install's folder with SHGetKnownFolderPath, then reads
    ; the result as a fixed ${NSIS_MAX_STRLEN}-character buffer: it reads past the end and now and
    ; then crashes the installer (System.dll, 0xC0000005). It skips that path when this user's
    ; install location is recorded, so a first install records the same folder here, read safely;
    ; a refused install removes it again.
    ReadRegStr $R4 HKCU "${INSTALL_REGISTRY_KEY}" InstallLocation
    ${If} $R4 == ""
      StrCpy $R4 "$LOCALAPPDATA\Programs"
      System::Call 'SHELL32::SHGetKnownFolderPath(g "{5CD7AEE2-2219-4A67-B85D-6C9CE15660CB}", i 0x8000, p 0, *p .r2) i .r1'
      ${If} $1 = 0
        System::Call 'kernel32::lstrcpyW(w .R4, p r2)'
      ${EndIf}
      System::Call 'OLE32::CoTaskMemFree(p r2)'
      WriteRegStr HKCU "${INSTALL_REGISTRY_KEY}" InstallLocation "$R4\${APP_FILENAME}"
      StrCpy $odinRecordedLocation "1"
    ${EndIf}
  !endif
!macroend

!macro customInit
  ; The per-user folder must be writable: an unwritable one stops here with help, never elevation.
  ClearErrors
  CreateDirectory "$INSTDIR"
  FileOpen $0 "$INSTDIR\.odin-install-check" w
  ${If} ${Errors}
    ${If} $odinRecordedLocation == "1"
      DeleteRegValue HKCU "${INSTALL_REGISTRY_KEY}" InstallLocation
      DeleteRegKey /ifempty HKCU "${INSTALL_REGISTRY_KEY}"
    ${EndIf}
    !insertmacro odinRefuse "Odin can't write to $INSTDIR, so the installer stopped. Check that the folder is yours and isn't read-only, then run the installer again."
  ${EndIf}
  FileClose $0
  Delete "$INSTDIR\.odin-install-check"
!macroend
