import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { flush, mount, type Host, type Mounted } from './component-host'
import type { ConfigField } from '../../src/shared/api'
import { settingsControlId } from '../../src/renderer/src/settings-accessibility'
let mounted: Mounted | undefined
let bridge: Record<string, any>
const ok = (result: unknown) => ({ ok: true, result })
const make = (path: string, desired: unknown, owner = 'settings.set', type: string = typeof desired, extra = {}): ConfigField => ({ path, desired, effective: desired, type, enum: null, constraints: {}, sensitivity: 'public', apply_handler: owner, apply_state: 'applied', nullable: desired === null, configured: null, ...extra } as ConfigField)
const fields = (hints: Record<string, string> = {}) => [
  make('llm_provider.model', 'codex:first', 'models.main.set'), make('llm_provider.active_provider', 'codex', 'models.main.set'),
  make('openai_codex.reasoning_effort', 'high', 'providers.codex.set', 'string', { enum: ['low', 'high', 'xhigh'] }),
  make('openai_codex.enabled', true, 'providers.codex.set'), make('openai_codex.context_utilization', 60, 'providers.codex.set', 'integer', { constraints: { minimum: 30, maximum: 100 } }),
  make('openai_compatible.context_utilization', 75, 'providers.compat.set', 'integer', { constraints: { minimum: 30, maximum: 100 } }),
  make('openai_compatible.enabled', false, 'providers.compat.set'), make('openai_compatible.base_url', 'https://example.test/v1', 'providers.compat.set'), make('openai_compatible.model', 'old', 'providers.compat.set'),
  make('openai_compatible.api_key', '[redacted]', 'providers.compat.set', 'string', { sensitivity: 'sensitive', secret_route: 'secrets.set', configured: true }),
  make('ollama.enabled', false, 'providers.ollama.set'), make('ollama.base_url', 'http://localhost:11434', 'providers.ollama.set'), make('ollama.model', 'old-local', 'providers.ollama.set'),
  make('agents.model', 'auto', 'models.agents.set'), make('agents.auto_model_allowlist', ['codex:first', { model: 'codex:second', reasoning_effort: 'high' }], 'models.agents.set', 'array'),
  make('agents.thinking_mode', null, 'models.agents.set', 'string', { enum: ['enabled', 'disabled'] }), make('agents.model_selection_hints', hints, 'models.agents.set', 'object'), make('agents.max_concurrent_agents', 3, 'settings.set', 'integer')
]
beforeEach(() => {
  vi.resetModules()
  bridge = {
    codexAccounts: vi.fn(async () => ok({ configured: true, accounts: [{ index: 0, email: 'person@example.test', is_current: true, quota: { primary: { used_percent: 0, window_minutes: 300, resets_at: 0 } } }] })),
    openrouterCatalogue: vi.fn(async () => ok({ recognized: true, models: [], quick_add: [] })),
    modelsStatus: vi.fn(async () => ok({ active_provider: 'codex', serving_provider: 'codex', ollama: { configured: true, base_url: 'http://127.0.0.1:11434', model: 'local' }, openai_compatible: { configured: false, model: 'openrouter/auto', base_url: 'https://openrouter.ai/api/v1', openrouter_recognized: true }, model_catalogue: { codex: ['first', 'second', 'new-second'].map((name) => ({ ref: `codex:${name}`, name, effort_capabilities: { values: name === 'first' ? ['low', 'high'] : ['high', 'xhigh'], restrictions_known: true, source: 'core_validation' } })) } })),
    settingsSchema: vi.fn(), status: vi.fn(async () => ({ ok: false, error: { code: 'unavailable', message: 'Not available' } })),
    providersCompatSet: vi.fn(), providersOllamaSet: vi.fn(), providersCodexSet: vi.fn(), settingsSet: vi.fn(), editLeaf: vi.fn(), secretsSet: vi.fn(), secretsClear: vi.fn()
  }
  ;(globalThis as any).window = { odin: bridge }
  ;(globalThis as any).document = { activeElement: null }
})
afterEach(() => { mounted?.unmount(); mounted = undefined })
async function models(hints: Record<string, string> = {}) {
  const { settings } = await import('../../src/renderer/src/stores/settings')
  const meta = { revision: 'rev-1', schema_version: 1, fields: fields(hints), status: { counts: {}, desired_revision: 'rev-1', effective_revision: null } }
  settings.meta = meta
  bridge.settingsSchema.mockImplementation(async () => ok(settings.meta))
  for (const name of ['providersCompatSet', 'providersOllamaSet', 'providersCodexSet', 'settingsSet']) bridge[name].mockImplementation(async ({ changes }: any) => {
    const changed = changes.map(({ path, value }: any) => ({ ...settings.meta!.fields.find((item) => item.path === path), desired: value, effective: value }))
    return ok({ revision: 'rev-2', fields: changed })
  })
  bridge.editLeaf.mockImplementation(async () => ok({ status: 'updated' }))
  bridge.secretsSet.mockImplementation(async () => ok({ status: 'stored' }))
  mounted = mount((await import('../../src/renderer/src/components/CodexAccounts.vue')).default); await flush()
  return { root: mounted.root, settings }
}
const control = (root: Host, id: string) => root.findAll((item) => item.props.id === id)[0]!
describe('UI v1 curated Models', () => {
  it('shows main and agent draft actions only when dirty, as the last card content', async () => {
    const { root } = await models()
    expect(root.findAll((item) => item.props.id === 'main-model-actions' || item.props.id === 'agent-model-actions')).toHaveLength(0)
    const refresh = root.button('Refresh model choices')
    expect(refresh.parent?.findAll((item) => item.props.id === settingsControlId('curated', 'llm_provider.model'))).toHaveLength(1)
    control(root, settingsControlId('curated', 'openai_codex.reasoning_effort')).fire('change', { target: { value: 'low' } })
    control(root, settingsControlId('curated', 'agents.model')).fire('change', { target: { value: 'main' } }); await flush()
    for (const id of ['main-model-actions', 'agent-model-actions']) {
      const actions = control(root, id)
      expect(actions.findAll((item) => item.tag === 'button').map((item) => item.textContent())).toEqual(['Save', 'Cancel'])
      expect(actions.parent!.children.filter((item) => item.tag !== '#comment' && item.tag !== '#text').at(-1)).toBe(actions)
      actions.button('Cancel').fire('click'); await flush()
      expect(root.findAll((item) => item.props.id === id)).toHaveLength(0)
    }
    expect(bridge.editLeaf).not.toHaveBeenCalled()
  })
  it('uses canonical serving provider, not a model draft, and places inactive context in Configure', async () => {
    const { root } = await models()
    const codexId = settingsControlId('curated', 'openai_codex.context_utilization')
    const compatId = settingsControlId('curated', 'openai_compatible.context_utilization')
    expect(root.findAll((item) => item.props.id === codexId)).toHaveLength(1)
    expect(root.findAll((item) => item.props.id === compatId)).toHaveLength(0)
    control(root, settingsControlId('curated', 'llm_provider.model')).fire('change', { target: { value: 'compat:unsaved' } }); await flush()
    expect(root.findAll((item) => item.props.id === codexId)).toHaveLength(1)
    root.named('Configure OpenAI-compatible').fire('click'); await flush()
    expect(control(root, 'provider-compat-setup').findAll((item) => item.props.id === compatId)).toHaveLength(1)
    const previous = await bridge.modelsStatus({})
    bridge.modelsStatus.mockResolvedValue(ok({ ...previous.result, serving_provider: 'compat' }))
    root.button('Refresh model choices').fire('click'); await flush()
    expect(root.findAll((item) => item.props.id === codexId)).toHaveLength(0)
    expect(root.findAll((item) => item.props.id === compatId)).toHaveLength(1)
    expect(control(root, 'provider-compat-setup').findAll((item) => item.props.id === compatId)).toHaveLength(0)
    expect(bridge.providersCompatSet).not.toHaveBeenCalled()
  })
  it('renders percent and core bounds, rejects invalid context and saves through its owner', async () => {
    const { root } = await models()
    const input = control(root, settingsControlId('curated', 'openai_codex.context_utilization'))
    expect(input.props).toMatchObject({ type: 'number', min: 30, max: 100, step: 1 })
    expect(root.textContent()).toContain('30% to 100%')
    expect(input.parent!.textContent()).toContain('%')
    input.type('29'); await flush()
    input.parent!.parent!.parent!.button('Save').fire('click'); await flush()
    expect(bridge.providersCodexSet).not.toHaveBeenCalled()
    expect(root.textContent()).toContain('The lowest is 30')
    input.type('80'); await flush()
    input.parent!.parent!.parent!.button('Save').fire('click'); await flush()
    expect(bridge.providersCodexSet).toHaveBeenCalledExactlyOnceWith({ expected_revision: 'rev-1', changes: [{ path: 'openai_codex.context_utilization', value: 80 }] })
  })
  it('keeps one account heading, details left, status/actions right and truthful provider summaries', async () => {
    const { root } = await models()
    expect(root.findAll((item) => item.tag === 'h4' && item.textContent() === 'Codex accounts')).toHaveLength(0)
    expect(root.button('Add account').parent?.parent?.props.class).toContain('settings-section-header')
    const account = root.findAll((item) => item.tag === 'li' && String(item.props.class).includes('account'))[0]!
    expect(account.children.filter((item) => item.tag === 'div').map((item) => item.props.class)).toEqual(['account-details', 'account-controls'])
    expect(account.children[0]!.textContent()).toContain('person@example.test')
    const controls = account.findAll((item) => item.props.class === 'account-controls')[0]!
    expect(controls.textContent()).toContain('In use')
    expect(controls.button('More').props['aria-haspopup']).toBe('menu')
    expect(controls.button('Refresh sign-in').props.role).toBe('menuitem')
    expect(controls.button('Rename').props.role).toBe('menuitem')
    expect(controls.button('Refresh sign-in')).toBeTruthy()
    expect(controls.button('Rename')).toBeTruthy()
    expect(root.textContent()).toContain('Signed in · 1 account')
    expect(root.textContent()).toContain('Configured · http://127.0.0.1:11434')
    expect(root.textContent()).toContain('OpenRouter · openrouter/auto')
    expect(root.textContent()).not.toContain('Configure first')
    expect(root.findAll((item) => item.tag === 'span' && ['Enabled', 'Disabled'].includes(item.textContent()))).toHaveLength(0)
    for (const provider of ['Codex', 'Ollama', 'OpenAI-compatible']) expect(root.findAll((item) => item.props['aria-label'] === `Enable ${provider}`)).toHaveLength(1)
  })
  it('renders unavailable provider metadata honestly and retains disabled configuration', async () => {
    const { root, settings } = await models()
    settings.meta!.fields = settings.meta!.fields.filter((item) => item.path !== 'llm_provider.active_provider')
    bridge.modelsStatus.mockResolvedValue(ok({}))
    root.button('Refresh model choices').fire('click'); await flush()
    expect(root.textContent()).toContain('Context use is unavailable until the active provider is known')
    expect(root.textContent()).toContain('Provider status unavailable')
    expect(root.findAll((item) => item.props.id === settingsControlId('curated', 'openai_codex.context_utilization'))).toHaveLength(0)
    root.named('Configure OpenAI-compatible').fire('click'); await flush()
    expect(control(root, 'provider-compat-setup').findAll((item) => item.props.id === settingsControlId('curated', 'openai_compatible.context_utilization'))).toHaveLength(1)
    bridge.modelsStatus.mockResolvedValue(ok({ serving_provider: 'ollama' }))
    root.button('Refresh model choices').fire('click'); await flush()
    expect(root.textContent()).toContain('Ollama context limits are under More options')
    expect(bridge.providersCompatSet).not.toHaveBeenCalled()
  })
  it('clears account readiness claims after read problems and avoids fake provider connection claims', async () => {
    const { root, settings } = await models()
    settings.codex.stale = true; await flush()
    expect(root.textContent()).toContain('Account status unavailable')
    expect(root.textContent()).not.toContain('Signed in · 1 account')
    settings.codex.stale = false
    settings.codex.status!.accounts = []; await flush()
    expect(root.textContent()).toContain('Not set up')
    bridge.modelsStatus.mockResolvedValue(ok({ serving_provider: 'codex', ollama: { configured: false, model: 'local', base_url: 'http://saved.test:11434' }, openai_compatible: { configured: false } }))
    root.button('Refresh model choices').fire('click'); await flush()
    expect(root.textContent()).toContain('Setup saved · http://saved.test:11434')
    expect(root.textContent()).not.toContain('Connected to')
  })
  it('hides agent actions when candidate changes return to the saved order', async () => {
    const { root } = await models()
    root.named('Move model 2 up').fire('click'); await flush()
    expect(control(root, 'agent-model-actions')).toBeTruthy()
    root.named('Move model 1 down').fire('click'); await flush()
    expect(root.findAll((item) => item.props.id === 'agent-model-actions')).toHaveLength(0)
    expect(bridge.editLeaf).not.toHaveBeenCalled()
  })
  it('keeps context immediately after main, quota zero, explicit owners and no schema paths', async () => {
    const { root } = await models()
    expect(root.findAll((item) => item.tag === 'h3').map((item) => item.textContent()).slice(0, 5)).toEqual(['Main model', 'Context', 'Agents', 'Accounts and quota', 'Providers'])
    expect(root.textContent()).toContain('0% of the 5-hour limit used')
    expect(root.textContent()).not.toContain('llm_provider.model')
    expect(root.textContent()).not.toContain('Reset to default')
    expect(bridge.editLeaf).not.toHaveBeenCalled()
  })
  it('configures disabled providers without blur writes or enabling, saves both values once', async () => {
    const { root, settings } = await models()
    root.named('Configure OpenAI-compatible').fire('click'); await flush()
    control(root, settingsControlId('curated', 'openai_compatible.base_url')).type('https://new.test/v1')
    control(root, settingsControlId('curated', 'openai_compatible.model')).type('new-model'); await flush()
    expect(bridge.providersCompatSet).not.toHaveBeenCalled()
    root.button('Save OpenAI-compatible setup').fire('click'); await flush()
    expect(bridge.providersCompatSet).toHaveBeenCalledExactlyOnceWith({ expected_revision: 'rev-1', changes: [{ path: 'openai_compatible.base_url', value: 'https://new.test/v1' }, { path: 'openai_compatible.model', value: 'new-model' }] })
    expect(settings.meta!.fields.find((item) => item.path === 'openai_compatible.enabled')!.desired).toBe(false)
  })
  it('preserves typing during a held provider receipt and keeps Cancel local', async () => {
    const { root } = await models()
    let settle!: (value: unknown) => void
    bridge.providersOllamaSet.mockImplementation(() => new Promise((resolve) => { settle = resolve }))
    root.named('Configure Ollama').fire('click'); await flush()
    const input = control(root, settingsControlId('curated', 'ollama.model'))
    input.type('first'); root.button('Save Ollama setup').fire('click'); await flush()
    input.type('newer'); await flush()
    settle(ok({ revision: 'rev-2', fields: [make('ollama.model', 'first', 'providers.ollama.set')] })); await flush()
    expect(input.value).toBe('newer')
    expect(root.textContent()).toContain('Unsaved changes')
    root.button('Cancel Ollama changes').fire('click'); await flush()
    expect(input.value).toBe('first')
    expect(bridge.providersOllamaSet).toHaveBeenCalledTimes(1)
  })
  it('submits main model and effort as one dedicated operation without silent downgrade', async () => {
    const { root } = await models()
    control(root, settingsControlId('curated', 'llm_provider.model')).fire('change', { target: { value: 'codex:second' } }); await flush()
    control(root, settingsControlId('curated', 'openai_codex.reasoning_effort')).fire('change', { target: { value: 'xhigh' } }); await flush()
    expect(bridge.editLeaf).not.toHaveBeenCalled()
    control(root, 'main-model-actions').button('Save').fire('click'); await flush()
    expect(bridge.editLeaf).toHaveBeenCalledExactlyOnceWith({ method: 'models.main.set', params: { model: 'codex:second', reasoning_effort: 'xhigh', expected_revision: 'rev-1' } })
  })
  it('uses projected per-model efforts and leaves incompatible drafts unsaved without downgrade', async () => {
    const { root } = await models()
    const effort = control(root, settingsControlId('curated', 'openai_codex.reasoning_effort'))
    expect(effort.findAll((item) => item.tag === 'option').map((item) => item.props.value)).toEqual(['low', 'high'])
    effort.fire('change', { target: { value: 'xhigh' } }); await flush()
    expect(effort.value).toBe('xhigh')
    expect(control(root, 'main-model-actions').button('Save').props.disabled).toBe(true)
    control(root, 'main-model-actions').button('Save').fire('click'); await flush()
    expect(bridge.editLeaf).not.toHaveBeenCalled()
    expect(root.textContent()).toContain('not changed automatically')
  })
  it('retains mixed candidate policies and ranking, and does not send keystrokes', async () => {
    const { root } = await models()
    control(root, settingsControlId('curated', 'agents.auto_model_allowlist.1.model')).fire('change', { target: { value: 'codex:new-second' } })
    root.named('Move model 2 up').fire('click'); await flush()
    expect(bridge.editLeaf).not.toHaveBeenCalled()
    control(root, 'agent-model-actions').button('Save').fire('click'); await flush()
    expect(bridge.editLeaf).toHaveBeenCalledExactlyOnceWith({ method: 'models.agents.set', params: { model: 'auto', auto_model_allowlist: [{ model: 'codex:new-second', reasoning_effort: 'high' }, 'codex:first'], expected_revision: 'rev-1' } })
  })
  it('shows each candidate\'s description and saves edits with the agent settings, not per keystroke', async () => {
    const { root } = await models({ 'codex:second': 'Long refactors' })
    const description = (index: number) => control(root, settingsControlId('curated', `agents.model_selection_hints.${index}`))
    expect(description(0).props.value).toBe('')
    expect(description(1).props.value).toBe('Long refactors')
    description(0).type('Quick lookups  '); await flush()
    description(1).type('  '); await flush()
    expect(description(0).props.value).toBe('Quick lookups  ')
    expect(description(1).props.value).toBe('')
    expect(bridge.editLeaf).not.toHaveBeenCalled()
    control(root, 'agent-model-actions').button('Save').fire('click'); await flush()
    expect(bridge.editLeaf).toHaveBeenCalledExactlyOnceWith({ method: 'models.agents.set', params: { model: 'auto', model_selection_hints: { 'codex:first': 'Quick lookups  ' }, expected_revision: 'rev-1' } })
  })
  it('keeps descriptions and the guidance JSON in one draft, so the newest edit in either is saved', async () => {
    const { root } = await models({ 'codex:second': 'Saved' })
    const description = (index: number) => control(root, settingsControlId('curated', `agents.model_selection_hints.${index}`))
    const guidance = () => control(root, settingsControlId('curated', 'agents.model_selection_hints'))
    guidance().type('{"codex:second": "Older JSON"}'); await flush()
    expect(description(1).props.value).toBe('Older JSON')
    description(1).type('Newest row'); await flush()
    expect(JSON.parse(String(guidance().props.value))).toEqual({ 'codex:second': 'Newest row' })
    description(0).type('Row text'); await flush()
    guidance().type('{"codex:first": "JSON wins"}'); await flush()
    expect([description(0).props.value, description(1).props.value]).toEqual(['JSON wins', ''])
    guidance().type('{"codex:first": '); await flush()
    expect(description(0).props.disabled).toBe(true)
    expect(root.textContent()).toContain('until the selection guidance under More options is valid JSON')
    description(0).type('ignored'); await flush()
    guidance().type('{"codex:first": "Fixed"}'); await flush()
    expect(description(0).props.disabled).toBe(false)
    control(root, 'agent-model-actions').button('Save').fire('click'); await flush()
    expect(bridge.editLeaf).toHaveBeenCalledExactlyOnceWith({ method: 'models.agents.set', params: { model: 'auto', model_selection_hints: { 'codex:first': 'Fixed' }, expected_revision: 'rev-1' } })
  })
  it('clears saved descriptions after the core trims them, and keeps an edit made while saving', async () => {
    const { root, settings } = await models()
    const description = (index: number) => control(root, settingsControlId('curated', `agents.model_selection_hints.${index}`))
    const actions = () => root.findAll((item) => item.props.id === 'agent-model-actions')
    const adopt = (params: any) => {
      const hints = Object.fromEntries(Object.entries(params.model_selection_hints as Record<string, string>).map(([model, hint]) => [model, hint.trim()]))
      settings.meta = { ...settings.meta!, revision: 'rev-2', fields: settings.meta!.fields.map((item) => item.path === 'agents.model_selection_hints' ? { ...item, desired: hints, effective: hints } : item) }
    }
    bridge.editLeaf.mockImplementation(async ({ params }: any) => { adopt(params); return ok({ status: 'updated' }) })
    description(0).type('  New hint  '); await flush()
    control(root, 'agent-model-actions').button('Save').fire('click'); await flush()
    expect(bridge.editLeaf.mock.calls[0]![0].params.model_selection_hints).toEqual({ 'codex:first': '  New hint  ' })
    expect(actions()).toHaveLength(0)
    expect(description(0).props.value).toBe('New hint')
    expect(root.textContent()).toContain('Saved.')
    let finish!: () => void
    bridge.editLeaf.mockImplementation(({ params }: any) => new Promise((resolve) => { finish = () => { adopt(params); resolve(ok({ status: 'updated' })) } }))
    description(0).type('First'); await flush()
    control(root, 'agent-model-actions').button('Save').fire('click'); await flush()
    description(0).type('Second'); await flush()
    finish(); await flush()
    expect(bridge.editLeaf.mock.calls[1]![0].params.model_selection_hints).toEqual({ 'codex:first': 'First' })
    expect(description(0).props.value).toBe('Second')
    expect(actions()).toHaveLength(1)
  })
  it('hides agent actions when descriptions return to their saved text, and Cancel restores them', async () => {
    const { root } = await models({ 'codex:second': 'Long refactors' })
    const description = (index: number) => control(root, settingsControlId('curated', `agents.model_selection_hints.${index}`))
    description(0).type('Quick lookups'); await flush()
    expect(control(root, 'agent-model-actions')).toBeTruthy()
    description(0).type(''); await flush()
    expect(root.findAll((item) => item.props.id === 'agent-model-actions')).toHaveLength(0)
    description(1).type('Something else'); await flush()
    control(root, 'agent-model-actions').button('Cancel').fire('click'); await flush()
    expect(description(1).props.value).toBe('Long refactors')
    expect(root.findAll((item) => item.props.id === 'agent-model-actions')).toHaveLength(0)
    root.button('Add automatic candidate').fire('click'); await flush()
    expect(description(2).props.disabled).toBe(true)
    expect(bridge.editLeaf).not.toHaveBeenCalled()
  })
  it('stores keys only explicitly, never reads secrets or includes them in provider saves', async () => {
    const { root } = await models()
    root.named('Configure OpenAI-compatible').fire('click'); await flush()
    const key = control(root, settingsControlId('curated', 'openai_compatible.api_key'))
    expect(key.value).toBe('')
    expect(root.textContent()).not.toContain('[redacted]')
    key.type('new-key'); await flush()
    expect(bridge.secretsSet).not.toHaveBeenCalled()
    root.named('Replace OpenAI-compatible API key').fire('click'); await flush()
    expect(bridge.secretsSet).toHaveBeenCalledExactlyOnceWith({ path: 'openai_compatible.api_key', value: 'new-key' })
    expect(key.value).toBe('')
    expect(bridge.providersCompatSet).not.toHaveBeenCalled()
  })
  it('clears submitted write-only keys after a refused store without replay', async () => {
    bridge.secretsSet.mockResolvedValue({ ok: false, error: { code: 'secret_locked', message: 'Key store is locked.' } })
    const { root } = await models()
    root.named('Configure OpenAI-compatible').fire('click'); await flush()
    const key = control(root, settingsControlId('curated', 'openai_compatible.api_key'))
    key.type('failed-write-only-key'); await flush()
    root.named('Replace OpenAI-compatible API key').fire('click'); await flush()
    expect(bridge.secretsSet).toHaveBeenCalledExactlyOnceWith({ path: 'openai_compatible.api_key', value: 'failed-write-only-key' })
    expect(key.value).toBe('')
    expect(root.textContent()).not.toContain('failed-write-only-key')
    root.named('Replace OpenAI-compatible API key').fire('click'); await flush()
    expect(bridge.secretsSet).toHaveBeenCalledTimes(1)
  })
  it('rejects unknown grouped save and fences later provider intent without replay', async () => {
    const { root, settings } = await models()
    bridge.providersOllamaSet.mockResolvedValue({ ok: false, error: { code: 'outcome_unknown', message: 'Unknown', disposition: 'outcome_unknown' } })
    root.named('Configure Ollama').fire('click'); await flush()
    control(root, settingsControlId('curated', 'ollama.model')).type('new'); root.button('Save Ollama setup').fire('click'); await flush()
    expect(settings.unknownSave).toBe(true)
    root.button('Save Ollama setup').fire('click'); await flush()
    expect(bridge.providersOllamaSet).toHaveBeenCalledTimes(1)
    expect(control(root, settingsControlId('curated', 'ollama.model')).value).toBe('new')
  })
  it('serializes provider and secret writes, taking the revision settled by the previous owner', async () => {
    const { settings } = await models()
    const { saveFields, setSecret } = await import('../../src/renderer/src/stores/settings')
    let settle!: (answer: unknown) => void
    bridge.providersOllamaSet.mockImplementation(() => new Promise((resolve) => { settle = resolve }))
    const saving = saveFields([{ field: settings.meta!.fields.find((item) => item.path === 'ollama.model')!, value: 'new' }])
    const key = setSecret(settings.meta!.fields.find((item) => item.path === 'openai_compatible.api_key')!, 'new-key')
    await flush()
    expect(bridge.secretsSet).not.toHaveBeenCalled()
    settle(ok({ revision: 'rev-2', fields: [make('ollama.model', 'new', 'providers.ollama.set')] }))
    expect(await saving).toBe(true)
    expect(await key).toBe(true)
    expect(bridge.secretsSet).toHaveBeenCalledTimes(1)
    expect(settings.meta!.revision).toBe('rev-2')
  })
  it('fences a grouped authority change while queued and does not replay against new metadata', async () => {
    const { settings } = await models()
    const { saveFields } = await import('../../src/renderer/src/stores/settings')
    let settle!: (answer: unknown) => void
    bridge.providersOllamaSet.mockImplementation(() => new Promise((resolve) => { settle = resolve }))
    const first = saveFields([{ field: settings.meta!.fields.find((item) => item.path === 'ollama.model')!, value: 'new' }])
    const second = saveFields([{ field: settings.meta!.fields.find((item) => item.path === 'openai_compatible.model')!, value: 'new-compatible' }])
    await flush()
    settings.meta!.fields.find((item) => item.path === 'openai_compatible.model')!.constraints.max_length = 5
    settle(ok({ revision: 'rev-2', fields: [make('ollama.model', 'new', 'providers.ollama.set')] }))
    expect(await first).toBe(true)
    expect(await second).toBe(false)
    expect(bridge.providersCompatSet).not.toHaveBeenCalled()
  })
  it('never calls a successful model receipt Saved after its refresh fails or Odin changes', async () => {
    const { settings } = await models()
    const { saveModelSettings } = await import('../../src/renderer/src/stores/settings')
    bridge.settingsSchema.mockResolvedValue({ ok: false, error: { code: 'offline', message: 'Could not read settings.' } })
    expect(await saveModelSettings('models.main.set', { model: 'codex:new', reasoning_effort: 'high' })).toBe(false)
    expect(settings.fields['llm_provider.model']?.status).toBe('error')
    bridge.settingsSchema.mockImplementation(async () => { (await import('../../src/renderer/src/store')).state.recoveryEpoch += 1; return ok(settings.meta) })
    expect(await saveModelSettings('models.main.set', { model: 'codex:new', reasoning_effort: 'high' })).toBe(false)
    expect(settings.unknownSave).toBe(true)
    expect(settings.fields['llm_provider.model']?.status).toBe('error')
  })
  it('serializes image intent behind secrets and marks settlement after an epoch change unconfirmed', async () => {
    const { settings } = await models()
    const { setSecret, setImageIntent } = await import('../../src/renderer/src/stores/settings')
    settings.meta!.image_models_revision = 'image-rev'
    let settle!: (answer: unknown) => void
    bridge.secretsSet.mockImplementation(() => new Promise((resolve) => { settle = resolve }))
    bridge.imageModelIntent = vi.fn(async () => ok({ image_models_revision: 'image-next' }))
    const first = setSecret(settings.meta!.fields.find((item) => item.path === 'openai_compatible.api_key')!, 'new-key')
    const second = setImageIntent('image_model', 'pin')
    await flush(); expect(bridge.imageModelIntent).not.toHaveBeenCalled()
    settle(ok({ stored: true })); expect(await first).toBe(true); expect(await second).toBe(true)
    expect(bridge.imageModelIntent).toHaveBeenCalledExactlyOnceWith({ expected_revision: 'image-rev', operations: { image_model: 'pin' } })
    bridge.imageModelIntent.mockImplementation(async () => { (await import('../../src/renderer/src/store')).state.recoveryEpoch += 1; return ok({ image_models_revision: 'image-next' }) })
    expect(await setImageIntent('image_model', 'follow')).toBe(false)
    expect(settings.fields['image.openai.image_model']?.status).toBe('error')
    expect(settings.unknownSave).toBe(true)
  })
  it('rejects out-of-order model choices and clears capabilities after failed refresh', async () => {
    let settle!: (answer: unknown) => void
    bridge.modelsStatus.mockImplementationOnce(() => new Promise((resolve) => { settle = resolve }))
    const { root } = await models()
    const effort = control(root, settingsControlId('curated', 'openai_codex.reasoning_effort'))
    root.button('Refresh model choices').fire('click'); await flush()
    expect(effort.findAll((item) => item.tag === 'option').map((item) => item.props.value)).toEqual(['low', 'high'])
    settle(ok({ model_catalogue: { codex: [{ ref: 'codex:first', effort_capabilities: { values: ['WRONG'], source: 'core_validation', restrictions_known: true } }] } })); await flush()
    expect(effort.textContent()).not.toContain('WRONG')
    bridge.modelsStatus.mockResolvedValue({ ok: false, error: { code: 'offline', message: 'Model choices offline' } })
    // Refresh remains available even after a successful read.
    root.button('Refresh model choices').fire('click'); await flush()
    expect(effort.props.disabled).toBe(true)
    expect(root.findAll((item) => item.props['data-testid'] === 'main-model-actions')).toHaveLength(0)
  })
})
